# Specify the MATLAB executable
MATLAB = matlab

# Specify the MATLAB script to run
SCRIPT = lab2_109611066.m

# Default target
all: run

# Target to run the MATLAB script
run:
	cd lab2/ && $(MATLAB) -nodesktop -r "run('$(SCRIPT)');"