run:
	cd scripts && python q1.py
	cd scripts && python q2.py
	cd scripts && python q3.py

install:
	pip install pandas
	pip install scipy
	pip install numpy
	pip install matplotlib
	pip install seaborn
	pip install statsmodels